### PR TITLE
Ssdt 64 build initial page for screener question 1

### PR DESCRIPTION
**Pull request by Kathp21**
## Description:

- Add responsive design for the screener question 
- Add function to buttons and routing. 

Add Screenshots (if applicable).

## Testing / Acceptance Criteria

- Step-by-step instructions on how to test the changes.
- Clear acceptance criteria that must be met for this pull request to be considered complete.

## Checklist:

- [X ] I have tested the changes locally.
- [ X] I have **requested review** from the other 2 developers on the project

### CODE REVIEW

**Comment by FireL0ki** [comment]
It looks like this has some merge conflicts that need to be handled before it can be merged -- could you merge those in and then I'll take a look?

**Comment by adrienne365** [comment]
Layout of each question looks great!

I see typos in both questions:
q1: currently "Are you transistion in new career?"
 please change to: "Are you transitioning in a new career?"

q2: currently "Are you aspiring to pursue a career as software enginnering?"
 please change to: "Are you aspiring to pursue a career as a software engineer?"

**Review by adrienne365 — CHANGES_REQUESTED** [review]
Layout of each question looks great!

I see typos in both questions:
q1: currently "Are you transistion in new career?"
please change to: "Are you transitioning in a new career?"

q2: currently "Are you aspiring to pursue a career as software enginnering?"
please change to: "Are you aspiring to pursue a career as a software engineer?"

Routes from buttons are not functioning on my end

**Review by Kathp21 — COMMENTED** [review]
Changed it!

**Comment by Kathp21** [comment]
> It looks like this has some merge conflicts that need to be handled before it can be merged -- could you merge those in and then I'll take a look?

- Merge conflicts solved

**Review by FireL0ki — APPROVED** [review]
Fixed a few typos, but other than that, this looks great! I made the typo updates, so I'll be merging this in. Thanks for the excellent work!

**Pull request merged**
